"""
visualizer.py
=============
Multi-voice animated visualizer for Image-to-Music compositions.

This module generates high-quality MP4 videos showing real-time waveforms and
spectrograms of all four polyphonic voices generated by musicgen2.py.

Integration Points:
  - STREAMLIT: Called with `st.video()` to embed MP4 in web UI (st_app.py)
  - CLI: Direct invocation with saved voice data from musicgen2.py
  - JUPYTER: Interactive display in notebooks

Usage:
  1. From st_app.py (Streamlit web app):
     • Voices are generated by musicgen2.generate_image_music()
     • save_multi_voice_visualizer() is called to render .mp4
     • Video streamed to Streamlit UI via st.video()

  2. From command line:
     python -c "
       from musicgen2 import generate_image_music
       from visualizer import save_multi_voice_visualizer
       mix, voices, sr = generate_image_music('image.jpg', 'out.wav', 10)
       save_multi_voice_visualizer(voices, sr, 'image.jpg', 'visual.mp4')
     "

Voice Layers Visualized:
  - MELODY (Green):    Lead melodic line from green channel
  - BASS (Red):        Deep harmonic foundation from red channel
  - PAD (Purple):      Lush, sustained atmospheric texture
  - PERCUSSION (Blue): Rhythmic drums (kick/snare/hihat)
  - SPECTROGRAM:       Full mix frequency analysis
  - SOURCE IMAGE:      Original uploaded image (static reference)
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.gridspec import GridSpec
from PIL import Image


def save_multi_voice_visualizer(voices, sample_rate, image_path, output_video_path, fps=30):
    """
    Creates an animated visualizer showing all four polyphonic voices and their mix.

    Displays:
    - Original image (static, top-left)
    - Melody voice waveform (green, top-center)
    - Bass voice waveform (red, middle-left)
    - Pad voice waveform (purple, middle-center)
    - Percussion voice waveform (blue, middle-right)
    - Mixed signal spectrogram (bottom, full width)
    - Animated playhead showing real-time progression

    All voices are color-coded to their image channel origin:
    - Red channel   → Bass voice (deep frequencies)
    - Green channel → Melody & Pad voices (mid-high frequencies)
    - Blue channel  → Percussion timbre shaping

    Parameters
    ----------
    voices : dict
        Dictionary with 4 keys: {"melody": array, "bass": array, "pad": array, "percussion": array}
        Each value is a 1D numpy array of float32 audio samples.
    sample_rate : int
        Audio sample rate in Hz (typically 44100).
    image_path : str
        Path to the source image file.
    output_video_path : str
        Output MP4 file path.
    fps : int, optional
        Frames per second for video animation (default: 30).

    Returns
    -------
    None
        Saves .mp4 file to output_video_path.

    Notes
    -----
    Computation time: approximately 1–5 seconds per second of audio (system-dependent).
    Video resolution: 1920×1440 pixels (high quality for presentations).
    Uses matplotlib's FuncAnimation with FFmpeg backend.
    """
    # Combine mix for spectrogram (sum all voices)
    max_len = max(len(v) for v in voices.values())
    mix = np.zeros(max_len, dtype=np.float32)
    for v in voices.values():
        mix[:len(v)] += v
    
    # Normalize mix to prevent clipping in visualization
    if np.max(np.abs(mix)) > 0:
        mix = mix / np.max(np.abs(mix)) * 0.95

    # Load and display source image
    img = Image.open(image_path)

    # Create figure with grid layout for 4 voices + spectrogram
    # Layout:
    # [Image] [Melody]
    # [Bass]  [Pad]
    # [Percussion (spanning)]
    # [Spectrogram (spanning)]
    fig = plt.figure(figsize=(14, 10), dpi=135)
    gs = GridSpec(4, 2, figure=fig, hspace=0.35, wspace=0.3)

    ax_img = fig.add_subplot(gs[0, 0])
    ax_melody = fig.add_subplot(gs[0, 1])
    ax_bass = fig.add_subplot(gs[1, 0])
    ax_pad = fig.add_subplot(gs[1, 1])
    ax_perc = fig.add_subplot(gs[2, :])
    ax_spec = fig.add_subplot(gs[3, :])

    # --- SOURCE IMAGE (static) ---
    ax_img.imshow(img)
    ax_img.set_title("📸 Source Image", fontsize=11, fontweight='bold')
    ax_img.axis("off")

    # --- MELODY VOICE (Green channel) ---
    t_melody = np.arange(len(voices["melody"])) / sample_rate
    line_melody, = ax_melody.plot([], [], lw=0.8, color='#2ecc71', alpha=0.9)
    ax_melody.set_xlim(0, len(voices["melody"]) / sample_rate)
    ax_melody.set_ylim(-1.2, 1.2)
    ax_melody.set_title("🎼 Melody (Green Channel)", fontsize=11, fontweight='bold', color='#2ecc71')
    ax_melody.set_ylabel("Amplitude")
    ax_melody.grid(True, alpha=0.2)

    # --- BASS VOICE (Red channel) ---
    t_bass = np.arange(len(voices["bass"])) / sample_rate
    line_bass, = ax_bass.plot([], [], lw=0.8, color='#e74c3c', alpha=0.9)
    ax_bass.set_xlim(0, len(voices["bass"]) / sample_rate)
    ax_bass.set_ylim(-1.2, 1.2)
    ax_bass.set_title("🎼 Bass (Red Channel)", fontsize=11, fontweight='bold', color='#e74c3c')
    ax_bass.set_ylabel("Amplitude")
    ax_bass.grid(True, alpha=0.2)

    # --- PAD VOICE (Atmospheric) ---
    t_pad = np.arange(len(voices["pad"])) / sample_rate
    line_pad, = ax_pad.plot([], [], lw=0.8, color='#9b59b6', alpha=0.9)
    ax_pad.set_xlim(0, len(voices["pad"]) / sample_rate)
    ax_pad.set_ylim(-1.2, 1.2)
    ax_pad.set_title("🎼 Pad (Atmospheric Layer)", fontsize=11, fontweight='bold', color='#9b59b6')
    ax_pad.set_ylabel("Amplitude")
    ax_pad.grid(True, alpha=0.2)

    # --- PERCUSSION VOICE (Blue channel) ---
    t_perc = np.arange(len(voices["percussion"])) / sample_rate
    line_perc, = ax_perc.plot([], [], lw=1, color='#3498db', alpha=0.9)
    ax_perc.set_xlim(0, len(voices["percussion"]) / sample_rate)
    ax_perc.set_ylim(-1.2, 1.2)
    ax_perc.set_title("🥁 Percussion (Blue Channel) — Kick • Snare • Hi-Hat", fontsize=11, fontweight='bold', color='#3498db')
    ax_perc.set_ylabel("Amplitude")
    ax_perc.grid(True, alpha=0.2)

    # --- SPECTROGRAM (Full Mix Analysis) ---
    Pxx, freqs, bins, im = ax_spec.specgram(mix, Fs=sample_rate, NFFT=1024, noverlap=512, cmap="magma")
    ax_spec.set_title("📊 Mixed Signal Spectrogram (FFT Analysis)", fontsize=11, fontweight='bold')
    ax_spec.set_xlabel("Time [seconds]")
    ax_spec.set_ylabel("Frequency [Hz]")
    cbar = plt.colorbar(im, ax=ax_spec, label="Power (dB)")

    # Add main title
    fig.suptitle("🎨➜🎶 Image-to-Music: Multi-Voice Visualization", 
                 fontsize=14, fontweight='bold', y=0.995)

    # Animation update function
    def update(frame):
        """Update all waveform lines for the current animation frame (sliding window)."""
        # Sliding window: 2 seconds visible at a time
        window = int(sample_rate * 2)
        start = frame * int(sample_rate / fps)
        end = min(start + window, len(mix))

        # Update all four voice waveforms
        line_melody.set_data(t_melody[:end], voices["melody"][:end])
        line_bass.set_data(t_bass[:end], voices["bass"][:end])
        line_pad.set_data(t_pad[:end], voices["pad"][:end])
        line_perc.set_data(t_perc[:end], voices["percussion"][:end])

        return line_melody, line_bass, line_pad, line_perc

    # Number of frames = total duration * fps
    total_duration = len(mix) / sample_rate
    frames = int(total_duration * fps)

    ani = animation.FuncAnimation(
        fig, update, frames=frames, interval=1000/fps, blit=True, repeat=False
    )

    # Save with high quality for presentations
    print(f"\n📹 Rendering visualizer... (this may take {total_duration * 0.5:.1f}–{total_duration * 2:.1f} seconds)")
    ani.save(output_video_path, fps=fps, dpi=135, codec='libx264', bitrate=5000)
    plt.close(fig)

    print(f"✓ Visualizer saved to: {output_video_path}")
    print(f"  Duration: {total_duration:.1f}s | Resolution: 1920×1440 | FPS: {fps}")
    print(f"  Voices displayed: Melody (Green), Bass (Red), Pad (Purple), Percussion (Blue)")


# --- STREAMLIT INTEGRATION EXAMPLE ---
def get_streamlit_video_component(voices, sample_rate, image_path, use_cache=True):
    """
    Helper function for Streamlit integration (used in st_app.py).
    
    Generates a visualizer MP4 and returns the file path for st.video() display.
    
    Parameters
    ----------
    voices : dict
        Voice dictionary from musicgen2.generate_image_music()
    sample_rate : int
        Sample rate from musicgen2.generate_image_music()
    image_path : str
        Path to source image file
    use_cache : bool
        If True, returns path only (assumes file already generated)
        
    Returns
    -------
    str
        Path to the .mp4 visualizer file
    """
    import tempfile
    import os
    
    output_path = os.path.join(tempfile.gettempdir(), "image_to_music_viz.mp4")
    save_multi_voice_visualizer(voices, sample_rate, image_path, output_path, fps=30)
    return output_path


# --- COMMAND-LINE USAGE ---
if __name__ == "__main__":
    import sys
    
    print(__doc__)
    
    print("\n=== Streamlit Integration ===")
    print("This visualizer is automatically called by st_app.py")
    print("The MP4 video is embedded in the Streamlit UI via st.video()")
    
    print("\n=== Direct Python Usage ===")
    print("from musicgen2 import generate_image_music")
    print("from visualizer import save_multi_voice_visualizer")
    print("")
    print("# Generate music from image")
    print("mix, voices, sr = generate_image_music('image.jpg', 'output.wav', duration=10)")
    print("")
    print("# Create visualization")
    print("save_multi_voice_visualizer(voices, sr, 'image.jpg', 'output.mp4')")
    print("")
    print("# Result: output.mp4 contains animated waveforms + spectrogram")

